services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kindred_butler
      POSTGRES_PASSWORD: "Ce72aUBnruNFW66uDczfUgdeo3zS3bLN"
    volumes:
      - kindred_butler_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "C9EDHYvbNGSwQ7ly8jxLLlWPkKfWAret"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kindred_butler_test
      POSTGRES_PASSWORD: "KC9o_AIQhYZwZ17eC7qH2un0zT3uEugX"
    volumes:
      - kindred_butler_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "PpCYEsnL-J5kRQ3LgJ5gG2xuRor5Eb7o"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  kindred_butler_data:
  kindred_butler_test_data: